// Frontend reference data for the Community & Small Business Opportunities
// section. Kept in src/ because backend modules under base44/ are server-only.

export const US_STATES = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "DC", name: "District of Columbia" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
];

// NTEE major groups, matching the IRS classification codes.
export const NTEE_GROUPS = [
  { code: "A", label: "Arts, Culture & Humanities" },
  { code: "B", label: "Education" },
  { code: "C", label: "Environment" },
  { code: "D", label: "Animal-Related" },
  { code: "E", label: "Health" },
  { code: "F", label: "Mental Health & Crisis Intervention" },
  { code: "G", label: "Diseases & Medical Disciplines" },
  { code: "H", label: "Medical Research" },
  { code: "I", label: "Crime & Legal-Related" },
  { code: "J", label: "Employment" },
  { code: "K", label: "Food, Agriculture & Nutrition" },
  { code: "L", label: "Housing & Shelter" },
  { code: "M", label: "Public Safety & Disaster Preparedness" },
  { code: "N", label: "Recreation & Sports" },
  { code: "O", label: "Youth Development" },
  { code: "P", label: "Human Services" },
  { code: "Q", label: "International & Foreign Affairs" },
  { code: "R", label: "Civil Rights & Advocacy" },
  { code: "S", label: "Community Improvement" },
  { code: "T", label: "Philanthropy & Grantmaking" },
  { code: "U", label: "Science & Technology" },
  { code: "V", label: "Social Science" },
  { code: "W", label: "Public & Societal Benefit" },
  { code: "X", label: "Religion-Related" },
  { code: "Y", label: "Mutual & Membership Benefit" },
  { code: "Z", label: "Unknown" },
];

export const PARTNER_STAGES = [
  { key: "new", label: "New", dot: "bg-secondary" },
  { key: "contacted", label: "Contacted", dot: "bg-primary" },
  { key: "meeting", label: "Meeting", dot: "bg-accent" },
  { key: "partner", label: "Partner", dot: "bg-emerald-500" },
  { key: "declined", label: "Declined", dot: "bg-foreground/40" },
];

export const NEED_TYPES = [
  { value: "personal_credit", label: "Help with my personal credit" },
  { value: "debt_help", label: "Help with personal debt" },
  { value: "business_credit", label: "Business credit or funding readiness" },
  { value: "financial_education", label: "Financial education or a workshop" },
  { value: "other", label: "Something else" },
];

export const ORG_TYPE_LABELS = {
  church: "Church",
  nonprofit: "Nonprofit",
  microbusiness: "Microbusiness",
};