// Official U.S. state business-registration sources — all 50 states + DC.
//
// This is an honest reference registry. Most jurisdictions expose a public
// business-entity search PORTAL but no automated API; those are marked
// MANUAL SEARCH ONLY. No state API endpoints, bulk feeds, or response schemas
// are invented. A jurisdiction is marked LIVE only after a real automated
// retrieval succeeds (none of the state portals qualify — they are manual).
//
// Statuses used: ready | needs_research | restricted
// automation_status: manual | restricted | needs_research | open_data
// source_type: manual_search | open_data | restricted | needs_research

export const STATE_BUSINESS_SOURCES = [
  { code:"AL", name:"Alabama", fips:"01", agency:"Secretary of State — Business Entities", official_url:"https://www.sos.alabama.gov/government-records/business-entities", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Public entity search portal. No automated API." },
  { code:"AK", name:"Alaska", fips:"02", agency:"Dept. of Commerce, Community & Econ. Development — Corporations", official_url:"https://www.commerce.alaska.gov/cbp/main/search/EntitySearch.aspx", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporations entity search portal." },
  { code:"AZ", name:"Arizona", fips:"04", agency:"Arizona Corporation Commission", official_url:"https://ecorp.azcc.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"eCorp public search portal." },
  { code:"AR", name:"Arkansas", fips:"05", agency:"Secretary of State — Business & Commercial Services", official_url:"https://www.sos.arkansas.gov/corps/search_all.php", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"CA", name:"California", fips:"06", agency:"Secretary of State — Business Programs (bizfile Online)", official_url:"https://bizfileonline.sos.ca.gov/", source_type:"bulk_data", api_available:false, open_data:false, bulk_data:true, automation_status:"needs_research", connection_status:"needs_research", free_paid:"Free (weekly bulk order; account required)", formation_date_available:true, data_format:"bizfile Online Bulk Order (weekly data & images)", update_frequency:"Weekly", automated:false, notes:"Free 'Bulk Order – Weekly Data & Images' available via bizfile Online (no fee), but requires a bizfile account and manual order placement — no automated API. A BE Public Search API exists but requires registration/key. NOT connected (no testable free automated endpoint)." },
  { code:"CO", name:"Colorado", fips:"08", agency:"Secretary of State — Business & Licensing", official_url:"https://coloradosos.gov/business/", source_type:"manual_search", api_available:false, open_data:true, bulk_data:false, automation_status:"open_data", connection_status:"needs_research", notes:"Open-data business filings reportedly available; bulk access needs verification." },
  { code:"CT", name:"Connecticut", fips:"09", agency:"Secretary of the State — Business Services Division", official_url:"https://data.ct.gov/Business/Connecticut-Business-Registry-Business-Master/n7gp-d28j", source_type:"open_data", api_available:true, open_data:true, bulk_data:true, automation_status:"live", connection_status:"live", free_paid:"Free", formation_date_available:true, data_format:"Socrata API (JSON/CSV)", update_frequency:"Daily", automated:true, notes:"Open-data Socrata API, public domain. date_registration = formation date. LIVE — automated retrieval confirmed." },
  { code:"DE", name:"Delaware", fips:"10", agency:"Division of Corporations — Secretary of State", official_url:"https://icis.corp.delaware.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"restricted", connection_status:"restricted", notes:"Public search restricted; automated bulk access restricted." },
  { code:"DC", name:"District of Columbia", fips:"11", agency:"DCRA — Corporations Division", official_url:"https://corp.dcra.dc.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Entity search portal." },
  { code:"FL", name:"Florida", fips:"12", agency:"Division of Corporations — Dept. of State (Sunbiz)", official_url:"https://dos.fl.gov/sunbiz/other-services/data-downloads/", source_type:"open_data", api_available:false, open_data:true, bulk_data:true, automation_status:"live", connection_status:"live", free_paid:"Free", formation_date_available:true, data_format:"Daily fixed-width text files (SFTP/HTTPS)", update_frequency:"Daily (work days)", automated:true, notes:"Free daily corporate filing downloads via public SFTP. Field 17 'File Date' = formation. LIVE — automated retrieval confirmed. Last 7 days fully covered; 30/90-day windows return the most recent business days." },
  { code:"GA", name:"Georgia", fips:"13", agency:"Secretary of State — Corporations (GTA Bulk Data)", official_url:"https://georgia.gov/bulk-corporations-data", source_type:"restricted", api_available:false, open_data:false, bulk_data:true, automation_status:"restricted", connection_status:"restricted", free_paid:"Paid", formation_date_available:true, data_format:"FTP subscription (tab-separated text)", update_frequency:"Monthly subscription", automated:false, notes:"PAID bulk data: $1,000 one-time OR $500/month + $100 account setup. Requires signed Bulk Corporations Data Agreement. Formation date included. NOT purchased — awaiting approval." },
  { code:"HI", name:"Hawaii", fips:"15", agency:"Dept. of Commerce & Consumer Affairs — Business Registration", official_url:"https://hbe.ehawaii.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Hawaii Business Express portal." },
  { code:"ID", name:"Idaho", fips:"16", agency:"Secretary of State — Business Entities", official_url:"https://www.sos.idaho.gov/corp/corpsearch.html", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"IL", name:"Illinois", fips:"17", agency:"Secretary of State — Department of Business Services", official_url:"https://www.ilsos.gov/data/bus-serv-home.html", source_type:"bulk_data", api_available:false, open_data:true, bulk_data:true, automation_status:"restricted", connection_status:"restricted", free_paid:"Free", formation_date_available:true, data_format:"Bulk ZIP files (fixed-width: Master, Names, Agents, Annual Report, Stock)", update_frequency:"Periodic (Business Data Transparency Act)", automated:false, notes:"Free bulk ZIP files (Corporations + LLC Master) published under the Business Data Transparency Act. HOWEVER the site's Terms of Use strictly prohibit automated queries to the website. NOT connected — automated use prohibited by ToS." },
  { code:"IN", name:"Indiana", fips:"18", agency:"Secretary of State — Business Services", official_url:"https://inbiz.in.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"INBiz portal." },
  { code:"IA", name:"Iowa", fips:"19", agency:"Secretary of State — Business Services", official_url:"https://sos.iowa.gov/search/business/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business entity search." },
  { code:"KS", name:"Kansas", fips:"20", agency:"Secretary of State — Business Entity", official_url:"https://www.kansas.gov/bess/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business entity search portal." },
  { code:"KY", name:"Kentucky", fips:"21", agency:"Secretary of State — Business Filings", official_url:"https://apps.sos.ky.gov/businessfilings/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business filings search." },
  { code:"LA", name:"Louisiana", fips:"22", agency:"Secretary of State — Commercial Division", official_url:"https://corporations.director.sos.la.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"ME", name:"Maine", fips:"23", agency:"Secretary of State — Corporations", official_url:"https://icrs.informe.org/nei-sos-icrs/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporate registration search." },
  { code:"MD", name:"Maryland", fips:"24", agency:"State Dept. of Assessments & Taxation (SDAT) — Charter Division", official_url:"https://egov.maryland.gov/businessexpress/CharterSearch", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", free_paid:"Free (search only)", formation_date_available:true, data_format:"Web search portal (Maryland Business Express)", update_frequency:"Real-time", automated:false, notes:"Maryland Business Express / SDAT charter search portal only. No open-data business-entity dataset found on opendata.maryland.gov (only property/SDAT assessments). MANUAL SEARCH ONLY." },
  { code:"MA", name:"Massachusetts", fips:"25", agency:"Secretary of the Commonwealth — Corporations Division", official_url:"https://www.sec.state.ma.us/divisions/corporations/corporations.htm", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", free_paid:"Free (search only)", formation_date_available:true, data_format:"Web search portal + annual Corporations Book (Excel)", update_frequency:"Annual (Corporations Book)", automated:false, notes:"SoS Corporations Database (search portal) + annual 'Corporations Book' tax list (published June 1 — a snapshot, not a new-business feed). No free API/open data with formation dates for new businesses. MANUAL SEARCH ONLY." },
  { code:"MI", name:"Michigan", fips:"26", agency:"Dept. of Licensing & Regulatory Affairs (LARA) — Corporations Division", official_url:"https://www.michigan.gov/lara/bureau-list/cscl/corps", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", free_paid:"Free (search only)", formation_date_available:true, data_format:"Web search portal (MiBusiness Registry)", update_frequency:"Real-time", automated:false, notes:"MiBusiness Registry Portal (search only). No open data, bulk data, or API found. MANUAL SEARCH ONLY." },
  { code:"MN", name:"Minnesota", fips:"27", agency:"Secretary of State — Business Services", official_url:"https://mblsportal.sos.state.mn.us/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business filings portal." },
  { code:"MS", name:"Mississippi", fips:"28", agency:"Secretary of State — Business Services", official_url:"https://corp.sos.ms.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"MO", name:"Missouri", fips:"29", agency:"Secretary of State — Business Services", official_url:"https://apps.sos.mo.gov/business/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business entity search." },
  { code:"MT", name:"Montana", fips:"30", agency:"Secretary of State — Business Services", official_url:"https://sosmt.gov/business/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business search portal." },
  { code:"NE", name:"Nebraska", fips:"31", agency:"Secretary of State — Business Services", official_url:"https://www.sos.ne.gov/business-services/business-portal", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business services portal." },
  { code:"NV", name:"Nevada", fips:"32", agency:"Secretary of State — Commercial Recordings", official_url:"https://esos.nv.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"eOSN business search." },
  { code:"NH", name:"New Hampshire", fips:"33", agency:"Secretary of State — Corporate Division", official_url:"https://www.sos.nh.gov/corporations", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"NJ", name:"New Jersey", fips:"34", agency:"Dept. of Treasury — Division of Revenue", official_url:"https://www.njportal.com/dor/businessnamesearch/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", free_paid:"Free (search only)", formation_date_available:true, data_format:"Web search portal", update_frequency:"Real-time", automated:false, notes:"Business name search portal only. No open data, bulk data, or API found. MANUAL SEARCH ONLY." },
  { code:"NM", name:"New Mexico", fips:"35", agency:"Secretary of State — Corporations", official_url:"https://portal.sos.state.nm.us/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"NY", name:"New York", fips:"36", agency:"Dept. of State — Division of Corporations", official_url:"https://data.ny.gov/Economic-Development/Daily-Corporation-and-Other-Entity-Filing-Data/k4vb-judh", source_type:"open_data", api_available:true, open_data:true, bulk_data:true, automation_status:"live", connection_status:"live", free_paid:"Free", formation_date_available:true, data_format:"Socrata API (JSON/CSV)", update_frequency:"Daily", automated:true, notes:"Free 'Daily Corporation and Other Entity Filing Data' — filings processed in the previous 30 days. filing_date field = formation/filing date. LIVE — automated retrieval confirmed." },
  { code:"NC", name:"North Carolina", fips:"37", agency:"Secretary of State — Corporations Division", official_url:"https://sosnc.gov/online_services/search/by_title/search_Business_Registration", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", free_paid:"Free (search only)", formation_date_available:true, data_format:"Web search portal", update_frequency:"Real-time", automated:false, notes:"Public business registration search portal only. No open data, bulk data, or API found. MANUAL SEARCH ONLY." },
  { code:"ND", name:"North Dakota", fips:"38", agency:"Secretary of State — Business Services", official_url:"https://firststop.sos.nd.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"FirstStop business portal." },
  { code:"OH", name:"Ohio", fips:"39", agency:"Secretary of State — Business Services Division", official_url:"https://www.ohiosos.gov/business/business-reports", source_type:"open_data", api_available:false, open_data:true, bulk_data:true, automation_status:"needs_research", connection_status:"error", free_paid:"Free", formation_date_available:true, data_format:"Monthly fixed-width TXT reports (New Business Entity Reports)", update_frequency:"Monthly (2nd Saturday)", automated:false, notes:"Free monthly 'New Business Entity Reports' (TXT) with Date of Incorporation. HOWEVER the file host (publicfiles.ohiosos.gov) returns HTTP 403 to programmatic/automated clients — automated retrieval blocked. NOT connected (access control respected; not bypassed)." },
  { code:"OK", name:"Oklahoma", fips:"40", agency:"Secretary of State — Business Filing", official_url:"https://www.sos.ok.gov/corp_info.htm", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"OR", name:"Oregon", fips:"41", agency:"Secretary of State — Corporation Division", official_url:"https://sos.oregon.gov/business/Pages/search.aspx", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business registry search." },
  { code:"PA", name:"Pennsylvania", fips:"42", agency:"Department of State — Bureau of Corporations", official_url:"https://data.pa.gov/Licenses-Certificates/Registered-Businesses-in-PA-Current-by-County-Depa/xvd7-5r2c", source_type:"open_data", api_available:true, open_data:true, bulk_data:true, automation_status:"live", connection_status:"live", free_paid:"Free", formation_date_available:true, data_format:"Socrata API (JSON/CSV)", update_frequency:"Daily", automated:true, notes:"Open-data Socrata API (dataset xvd7-5r2c), public, no token. creationdate = formation/registration date. LIVE — automated retrieval confirmed." },
  { code:"RI", name:"Rhode Island", fips:"44", agency:"Secretary of State — Business Portal", official_url:"https://sos.ri.gov/divisions/Business-Portal", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business entity search." },
  { code:"SC", name:"South Carolina", fips:"45", agency:"Secretary of State — Business Filings", official_url:"https://businessfilings.sc.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business filings search." },
  { code:"SD", name:"South Dakota", fips:"46", agency:"Secretary of State — Business Services", official_url:"https://sos.sd.gov/businessservices/corp.aspx", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"TN", name:"Tennessee", fips:"47", agency:"Secretary of State — Business Services", official_url:"https://tnbear.tn.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"TNBear business search." },
  { code:"TX", name:"Texas", fips:"48", agency:"Secretary of State — Corporations (SOSDirect)", official_url:"https://www.sos.state.tx.us/corp/sosda/index.shtml", source_type:"restricted", api_available:false, open_data:false, bulk_data:true, automation_status:"restricted", connection_status:"restricted", free_paid:"Paid", formation_date_available:true, data_format:"Paid bulk order via SOSDirect", update_frequency:"On request", automated:false, notes:"SOSDirect charges a $1.00 statutorily authorized fee per search. Bulk business-organization data files available for a fee. No free API/open data. NOT purchased — awaiting approval." },
  { code:"UT", name:"Utah", fips:"49", agency:"Dept. of Commerce — Division of Corporations", official_url:"https://secure.utah.gov/bes/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business entity search portal." },
  { code:"VT", name:"Vermont", fips:"50", agency:"Secretary of State — Corporations", official_url:"https://www.vt-sos.com/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporate registration search." },
  { code:"VA", name:"Virginia", fips:"51", agency:"State Corporation Commission — Clerk's Office", official_url:"https://data.virginia.gov/organization/state-corporate-commission", source_type:"open_data", api_available:false, open_data:true, bulk_data:true, automation_status:"needs_research", connection_status:"needs_research", free_paid:"Free", formation_date_available:false, data_format:"Bulk CSV downloads (LLC, Corporation, LP — DKAN portal)", update_frequency:"Monthly", automated:false, notes:"Virginia Open Data Portal publishes SCC bulk CSV datasets (LLC, Corporation, LP, etc.). DKAN-based (no queryable date-filter API). CSV download endpoint returned 404 during testing; formation-date column unverified. NOT connected — needs technical work (large-file handling + date-field verification)." },
  { code:"WA", name:"Washington", fips:"53", agency:"Secretary of State — Corporations & Charities", official_url:"https://ccfs.sos.wa.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporations search portal." },
  { code:"WV", name:"West Virginia", fips:"54", agency:"Secretary of State — Business & Licensing", official_url:"https://sosapps.wv.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business entity search." },
  { code:"WI", name:"Wisconsin", fips:"55", agency:"Dept. of Financial Institutions — Corporations", official_url:"https://www.wdfi.org/apps/CorpSearch/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"DFI corporation search." },
  { code:"WY", name:"Wyoming", fips:"56", agency:"Secretary of State — Business Division", official_url:"https://wyobiz.wyo.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business search portal." },
];

// Quick 2-letter → FIPS lookup for Census API calls.
export const STATE_FIPS = STATE_BUSINESS_SOURCES.reduce((m, s) => {
  m[s.code] = s.fips;
  return m;
}, {});

export function getSourceByCode(code) {
  return STATE_BUSINESS_SOURCES.find((s) => s.code === (code || "").toUpperCase()) || null;
}