// Official U.S. state business-registration sources — all 50 states + DC.
//
// This is an honest reference registry. Most jurisdictions expose a public
// business-entity search PORTAL but no automated API; those are marked
// MANUAL SEARCH ONLY. No state API endpoints, bulk feeds, or response schemas
// are invented. A jurisdiction is marked LIVE only after a real automated
// retrieval succeeds (none of the state portals qualify — they are manual).
//
// Statuses used: ready | needs_research | restricted
// automation_status: manual | restricted | needs_research | open_data
// source_type: manual_search | open_data | restricted | needs_research

export const STATE_BUSINESS_SOURCES = [
  { code:"AL", name:"Alabama", fips:"01", agency:"Secretary of State — Business Entities", official_url:"https://www.sos.alabama.gov/government-records/business-entities", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Public entity search portal. No automated API." },
  { code:"AK", name:"Alaska", fips:"02", agency:"Dept. of Commerce, Community & Econ. Development — Corporations", official_url:"https://www.commerce.alaska.gov/cbp/main/search/EntitySearch.aspx", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporations entity search portal." },
  { code:"AZ", name:"Arizona", fips:"04", agency:"Arizona Corporation Commission", official_url:"https://ecorp.azcc.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"eCorp public search portal." },
  { code:"AR", name:"Arkansas", fips:"05", agency:"Secretary of State — Business & Commercial Services", official_url:"https://www.sos.arkansas.gov/corps/search_all.php", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"CA", name:"California", fips:"06", agency:"Secretary of State — Business Programs", official_url:"https://businesssearch.sos.ca.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business search portal." },
  { code:"CO", name:"Colorado", fips:"08", agency:"Secretary of State — Business & Licensing", official_url:"https://coloradosos.gov/business/", source_type:"manual_search", api_available:false, open_data:true, bulk_data:false, automation_status:"open_data", connection_status:"needs_research", notes:"Open-data business filings reportedly available; bulk access needs verification." },
  { code:"CT", name:"Connecticut", fips:"09", agency:"Secretary of State — Commercial Recording", official_url:"https://portal.ct.gov/sots", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"CONCORD business search portal." },
  { code:"DE", name:"Delaware", fips:"10", agency:"Division of Corporations — Secretary of State", official_url:"https://icis.corp.delaware.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"restricted", connection_status:"restricted", notes:"Public search restricted; automated bulk access restricted." },
  { code:"DC", name:"District of Columbia", fips:"11", agency:"DCRA — Corporations Division", official_url:"https://corp.dcra.dc.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Entity search portal." },
  { code:"FL", name:"Florida", fips:"12", agency:"Division of Corporations — Dept. of State", official_url:"https://search.sunbiz.org/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Sunbiz public search portal." },
  { code:"GA", name:"Georgia", fips:"13", agency:"Secretary of State — Corporations", official_url:"https://ecorp.sos.state.ga.us/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"eCorp search portal." },
  { code:"HI", name:"Hawaii", fips:"15", agency:"Dept. of Commerce & Consumer Affairs — Business Registration", official_url:"https://hbe.ehawaii.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Hawaii Business Express portal." },
  { code:"ID", name:"Idaho", fips:"16", agency:"Secretary of State — Business Entities", official_url:"https://www.sos.idaho.gov/corp/corpsearch.html", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"IL", name:"Illinois", fips:"17", agency:"Secretary of State — Business Services", official_url:"https://www.ilsos.gov/corporatellc/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation/LLC search portal." },
  { code:"IN", name:"Indiana", fips:"18", agency:"Secretary of State — Business Services", official_url:"https://inbiz.in.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"INBiz portal." },
  { code:"IA", name:"Iowa", fips:"19", agency:"Secretary of State — Business Services", official_url:"https://sos.iowa.gov/search/business/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business entity search." },
  { code:"KS", name:"Kansas", fips:"20", agency:"Secretary of State — Business Entity", official_url:"https://www.kansas.gov/bess/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business entity search portal." },
  { code:"KY", name:"Kentucky", fips:"21", agency:"Secretary of State — Business Filings", official_url:"https://apps.sos.ky.gov/businessfilings/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business filings search." },
  { code:"LA", name:"Louisiana", fips:"22", agency:"Secretary of State — Commercial Division", official_url:"https://corporations.director.sos.la.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"ME", name:"Maine", fips:"23", agency:"Secretary of State — Corporations", official_url:"https://icrs.informe.org/nei-sos-icrs/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporate registration search." },
  { code:"MD", name:"Maryland", fips:"24", agency:"State Dept. of Assessments & Taxation — Charter", official_url:"https://egov.maryland.gov/businessexpress/CharterSearch", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Charter search portal." },
  { code:"MA", name:"Massachusetts", fips:"25", agency:"Secretary of State — Corporations Division", official_url:"https://corp.sec.state.ma.us/corpweb/CorpSearch/CorpSearch.aspx", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"MI", name:"Michigan", fips:"26", agency:"Dept. of Licensing & Regulatory Affairs — Corporations", official_url:"https://mdosservicealerts.michigan.gov/LaraBusinessSearch/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"LARA business entity search." },
  { code:"MN", name:"Minnesota", fips:"27", agency:"Secretary of State — Business Services", official_url:"https://mblsportal.sos.state.mn.us/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business filings portal." },
  { code:"MS", name:"Mississippi", fips:"28", agency:"Secretary of State — Business Services", official_url:"https://corp.sos.ms.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"MO", name:"Missouri", fips:"29", agency:"Secretary of State — Business Services", official_url:"https://apps.sos.mo.gov/business/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business entity search." },
  { code:"MT", name:"Montana", fips:"30", agency:"Secretary of State — Business Services", official_url:"https://sosmt.gov/business/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business search portal." },
  { code:"NE", name:"Nebraska", fips:"31", agency:"Secretary of State — Business Services", official_url:"https://www.sos.ne.gov/business-services/business-portal", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business services portal." },
  { code:"NV", name:"Nevada", fips:"32", agency:"Secretary of State — Commercial Recordings", official_url:"https://esos.nv.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"eOSN business search." },
  { code:"NH", name:"New Hampshire", fips:"33", agency:"Secretary of State — Corporate Division", official_url:"https://www.sos.nh.gov/corporations", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"NJ", name:"New Jersey", fips:"34", agency:"Dept. of Treasury — Division of Revenue", official_url:"https://www.njportal.com/DOR/BusinessNameSearch/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business name search portal." },
  { code:"NM", name:"New Mexico", fips:"35", agency:"Secretary of State — Corporations", official_url:"https://portal.sos.state.nm.us/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"NY", name:"New York", fips:"36", agency:"Dept. of State — Division of Corporations", official_url:"https://apps.dos.ny.gov/publicinquiry/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Entity search portal." },
  { code:"NC", name:"North Carolina", fips:"37", agency:"Secretary of State — Corporations", official_url:"https://www.sosnc.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"ND", name:"North Dakota", fips:"38", agency:"Secretary of State — Business Services", official_url:"https://firststop.sos.nd.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"FirstStop business portal." },
  { code:"OH", name:"Ohio", fips:"39", agency:"Secretary of State — Business Services", official_url:"https://businesssearch.ohiosos.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business search portal." },
  { code:"OK", name:"Oklahoma", fips:"40", agency:"Secretary of State — Business Filing", official_url:"https://www.sos.ok.gov/corp_info.htm", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"OR", name:"Oregon", fips:"41", agency:"Secretary of State — Corporation Division", official_url:"https://sos.oregon.gov/business/Pages/search.aspx", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business registry search." },
  { code:"PA", name:"Pennsylvania", fips:"42", agency:"Dept. of State — Bureau of Corporations", official_url:"https://www.corporations.pa.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business search portal." },
  { code:"RI", name:"Rhode Island", fips:"44", agency:"Secretary of State — Business Portal", official_url:"https://sos.ri.gov/divisions/Business-Portal", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business entity search." },
  { code:"SC", name:"South Carolina", fips:"45", agency:"Secretary of State — Business Filings", official_url:"https://businessfilings.sc.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business filings search." },
  { code:"SD", name:"South Dakota", fips:"46", agency:"Secretary of State — Business Services", official_url:"https://sos.sd.gov/businessservices/corp.aspx", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporation search portal." },
  { code:"TN", name:"Tennessee", fips:"47", agency:"Secretary of State — Business Services", official_url:"https://tnbear.tn.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"TNBear business search." },
  { code:"TX", name:"Texas", fips:"48", agency:"Secretary of State — Corporations", official_url:"https://direct.sos.state.tx.us/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"SOSDirect search portal." },
  { code:"UT", name:"Utah", fips:"49", agency:"Dept. of Commerce — Division of Corporations", official_url:"https://secure.utah.gov/bes/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business entity search portal." },
  { code:"VT", name:"Vermont", fips:"50", agency:"Secretary of State — Corporations", official_url:"https://www.vt-sos.com/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporate registration search." },
  { code:"VA", name:"Virginia", fips:"51", agency:"State Corporation Commission — Clerk's Office", official_url:"https://cis.scc.virginia.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Clerk's Information System search." },
  { code:"WA", name:"Washington", fips:"53", agency:"Secretary of State — Corporations & Charities", official_url:"https://ccfs.sos.wa.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Corporations search portal." },
  { code:"WV", name:"West Virginia", fips:"54", agency:"Secretary of State — Business & Licensing", official_url:"https://sosapps.wv.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business entity search." },
  { code:"WI", name:"Wisconsin", fips:"55", agency:"Dept. of Financial Institutions — Corporations", official_url:"https://www.wdfi.org/apps/CorpSearch/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"DFI corporation search." },
  { code:"WY", name:"Wyoming", fips:"56", agency:"Secretary of State — Business Division", official_url:"https://wyobiz.wyo.gov/", source_type:"manual_search", api_available:false, open_data:false, bulk_data:false, automation_status:"manual", connection_status:"ready", notes:"Business search portal." },
];

// Quick 2-letter → FIPS lookup for Census API calls.
export const STATE_FIPS = STATE_BUSINESS_SOURCES.reduce((m, s) => {
  m[s.code] = s.fips;
  return m;
}, {});

export function getSourceByCode(code) {
  return STATE_BUSINESS_SOURCES.find((s) => s.code === (code || "").toUpperCase()) || null;
}